language: node_js

node_js:
  - '10'

branchs:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_94a4da176068_key -iv $encrypted_94a4da176068_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

after_success:
  - ssh root@45.77.187.221 "/data/deploy.bash"

addons:
  ssh_known_hosts: 45.77.187.221
